name: ncatest.cx.js
 
on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 5 * * *'   #国际标准时间，北京时间+8，即下午1点钟
 
jobs:
  run-csjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '14'
          
      - name: Install Dependency       
        run: |
          # 安装
npm install -g @catlair/bilitools
# 查看帮助
bilitools -h
# 指定配置路径运行
bilitools -c ./config.json        
          node ./index.js  #脚本存在根目录scripts文件夹下
 
